
[window]

opacity = 0.8

padding.x = 10
padding.y = 10

decorations = "Full"
decorations_theme_variant = "Dark" # "Light"

[font]
normal = { family = "JetBrainsMono Nerd Font Mono", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font Mono", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font Mono", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font Mono", style = "Bold Italic" }
size = 12.0

[keyboard]
bindings = [
    { key = "L", mods = "Control", action = "ReceiveChar" }
]
